CREATE TABLE accounts (
    id BIGINT(20) UNSIGNED PRIMARY KEY,
    username VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户名',
    password VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
)ENGINE=InnoDB CHARSET=utf8mb4 COMMENT='账户表' COLLATE=utf8mb4_unicode_ci;