mode: debug
database:
  dsn: mysql://root:toor@tcp(localhost)/main?collation=utf8mb4_general_ci&loc=Asia/Shanghai&parseTime=true
baseUrl: http://localhost
queue:
  enable: false
storage:
  path: ./storage
  driver: local
  url: http://localhost/storage
